### ISSUE TITLE
Likely user error

### ISSUE THREAD

**Issue by awoods** [srerickson/ocfl-index#5]
After building `ocfl-index`, the following command results in the following output:
```
source config
./main index --s3-bucket [my-bucket]
```
..where "config" contains the `export AWS_...` credentials.

Output:
```
indexing to index.sqlite, schema: v0.1
2022/07/24 09:20:25 using FS dir=.
2022/07/24 09:20:25 reading storage root: not an ocfl storage root: NAMASTE declaration not found
```

**Comment by srerickson** [comment]
Both the `--s3-bucket` and `--s3-path` flags are required to turn on the S3 backend.  If the storage root doesn't have a path/prefix in the bucket (i.e., it's at the top level), use `--s3-path="."`. The documentation and error messages can definitely be more helpful in this case. 

Thanks for the user feedback!

**Comment by awoods** [comment]
Thanks, @srerickson . That worked... however, the results are questionable. See https://github.com/srerickson/ocfl-index/issues/7
