### ISSUE TITLE
Unexpected results: S3

### ISSUE THREAD

**Issue by awoods** [srerickson/ocfl-index#7]
The following command produces the following results:
```
$ time ./main index --s3-bucket [my-bucket] --s3-path .
2022/07/24 16:08:26 created new index tables
indexing to index.sqlite, schema: v0.1
2022/07/24 16:08:26 using S3 bucket=[my-bucket] path=.
scanning for objects...found 1435
indexed 1435/1435 objects
done

real	14m40.187s
user	0m20.607s
sys	0m16.283s
```

However, the bucket actually contains 10,093 objects. The following command produced the [linked output](https://gist.github.com/awoods/cc1bb259d7212492120dcc4470e91bb8). Note, there are 7141 top-level object directories in this S3 storage root.
```
aws s3 ls --profile [my-profile] s3://[my-bucket] --recursive | grep ocfl_object > objects.txt
```

**Comment by srerickson** [comment]
Thanks, @awoods, for the submitting this issue. I was able to reproduce the problem, which was caused by a bug in the underlying OCFL library. There's a new release of both `github.com/srerickson/ocfl-index` and `github.com/srerickson/ocfl` that should resolve the problem.

**Comment by awoods** [comment]
Using 0.0.4:
```
time bin/0.0.4/ocfl-index index --s3-bucket [my-bucket] --s3-path .
indexing to index.sqlite, schema: v0.1
2022/07/25 13:46:18 using S3 bucket=[my-bucket] path=.
2022/07/25 13:46:20 reading storage root: 0007-n-tuple-omit-prefix-storage-layout: unrecognized extension

real	0m1.894s
user	0m0.156s
sys	0m0.050s
```

**Comment by srerickson** [comment]
@awoods , this looks like a new issue that I'll track as #9.
