### ISSUE TITLE
Failure to load large S3 storage root

### ISSUE THREAD

**Issue by awoods** [srerickson/ocfl-index#8]
For an S3 storage root with the same structure as https://github.com/srerickson/ocfl-index/issues/7, but with 10,000 top-level object directories and 147,192 total OCFL objects, the following command produces the following results:
```
time ./main index --s3-bucket [my-bucket-2] --s3-path .
2022/07/24 16:50:12 created new index tables
indexing to index.sqlite, schema: v0.1
2022/07/24 16:50:12 using S3 bucket=[my-bucket-2] path=.
2022/07/24 16:50:13 reading storage root: not an ocfl storage root: NAMASTE declaration not found

real	0m1.844s
user	0m0.043s
sys	0m0.037s
```

It is possible that an OCFL object is corrupted in this storage root, but I have no particular reason to believe that is the case.

**Comment by srerickson** [comment]
My guess is that v0.0.4 would give the same error for this storage root that you recently reported in #7: "`0007-n-tuple-omit-prefix-storage-layout: unrecognized extension`".

**Comment by awoods** [comment]
Agreed. But it seems that neither the extensions directory nor storage root NAMASTE file are being read. Is it possible that the indexer quits before reading all of the top-level contents of the bucket?

**Comment by srerickson** [comment]
My hope was that the v0.0.4 update would fix the issue with the NAMASTE file and extensions directory not being read. For earlier versions, only 1000 top-level items would be listed -- so, if the NAMASTE file and extensions directory weren't in the first 1,000, they wouldn't be found or read. If that's still happening with v0.0.4, then there's something else going on that I haven't figure out yet.

**Comment by awoods** [comment]
The command and results in the description of this issue are using v0.0.4.

**Comment by srerickson** [comment]
I'm closing this because it's a bit stale and I haven't encountered any related problems in a while.
