### ISSUE TITLE
indexing shouldn't fail if storage layout is unrecognized

### ISSUE THREAD

**Issue by srerickson** [srerickson/ocfl-index#9]
Indexing fails if the storage root uses a layout extension that the underlying OCFL package doesn't support. This behavior doesn't make sense because the layout doesn't affect the indexing process.

**Comment by srerickson** [comment]
@awoods, there is [a new release](https://github.com/srerickson/ocfl-index/releases/tag/v0.0.5) that should resolve this issue (and hopefully #7)

**Comment by awoods** [comment]
Initial results:
```
$time bin/0.0.5/ocfl-index index --s3-bucket [my-bucket] --s3-path .
2022/08/05 20:15:44 ocfl-index 0.0.5
2022/08/05 20:15:44 indexing to index.sqlite, ocfl-index schema: v0.1
2022/08/05 20:15:44 using S3 bucket=[my-bucket] path=.
2022/08/05 20:15:48 starting object scan (concurrency=4)
2022/08/05 21:00:24 scan finished in 2676.51 sec., indexing 10095 objects ...
2022/08/05 23:24:31 indexing finished in 8647.07 sec. (total time 11323.58 sec.)

real	188m47.236s
user	3m1.741s
sys	2m23.801s
```

The number of objects seems correct; and the unknown layout extension did not cause failure. 

Do you you have example queries you would suggest I execute on the produced "index.sqlite"?

**Comment by srerickson** [comment]
@awoods, It looks like this is working as expected. The primary way to interact with index is through the `query` sub-command. Here are examples from the README:

```sh
# list all objects in the index
ocfl-index query

# list all versions in an object
ocfl-index query object-id

# list names of files and directories in the root of an object's most recent version
ocfl-index query object-id "."

# list names in the 'foo' directory of the object's first version
ocfl-index query object-id "foo" -v v1
```
The query command also has a `json` flag if you want to output the data as json.
